name: ScrapeNYC
on: 
  schedule:
    - cron: "59 4,16 * * *"
  workflow_dispatch:
jobs:
  Build-Docs-For-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: day="data/$(date +"%Y-%m-%d_T%H").json"; scrapy runspider MonkeypoxSpider.py -O $day
      - name: Commit report
        run: |
          git config --global user.name 'kaftand'
          git config --global user.email 'kaftand@users.noreply.github.com'
          git add data/*
          git commit -m "Automated report"
          git push